/*
* Generated file
*
* Generated from: yang module name: task-consumer-impl yang module local name: task-consumer-service
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Fri May 22 07:01:22 EDT 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.task_consumer.impl;
@org.opendaylight.controller.config.api.annotations.ServiceInterfaceAnnotation(value = "(urn:opendaylight:params:xml:ns:yang:controller:config:task-consumer:impl?revision=2014-05-23)task-consumer-service", osgiRegistrationType = de.dailab.nemo.ima.controller.consumer.TaskConsumerService.class, namespace = "urn:opendaylight:params:xml:ns:yang:controller:config:task-consumer:impl", revision = "2014-05-23", localName = "task-consumer-service")

@org.opendaylight.yangtools.yang.binding.annotations.ModuleQName(namespace = "urn:opendaylight:params:xml:ns:yang:controller:config:task-consumer:impl", revision = "2014-05-23", name = "task-consumer-impl")

public interface TaskConsumerServiceServiceInterface extends org.opendaylight.controller.config.api.annotations.AbstractServiceInterface {

}
